# Generated by Django 4.2 on 2025-03-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('war', 'Великая Отечественная Война'), ('tatneft', 'Татнефть')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
